### ⭐ 데이터 프레임 함수 연습!!!
✔️ [파일] - [Drive에 사본 저장]

### 1. 데이터 불러오기

📍 **시본(Seaborn) 라이브러리**? matplotlib를 기반으로 확장한 파이썬 시각화 라이브러리

In [ ]:
import seaborn
seaborn.get_dataset_names() # 시본 라이브러리에 해당하는 전체 데이터셋 목록 확인 가능

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
df = seaborn.load_dataset('anagrams') # ‘anagrams’ 데이터셋을 불러오기
df

    subidr    attnr  num1  num2  num3
0        1  divided     2   4.0     7
1        2  divided     3   4.0     5
2        3  divided     3   5.0     6
3        4  divided     5   7.0     5
4        5  divided     4   5.0     8
5        6  divided     5   5.0     6
6        7  divided     5   4.5     6
7        8  divided     5   7.0     8
8        9  divided     2   3.0     7
9       10  divided     6   5.0     6
10      11  focused     6   5.0     6
11      12  focused     8   9.0     8
12      13  focused     6   5.0     9
13      14  focused     8   8.0     7
14      15  focused     8   8.0     7
15      16  focused     6   8.0     7
16      17  focused     7   7.0     6
17      18  focused     7   8.0     6
18      19  focused     5   6.0     6
19      20  focused     6   6.0     5

In [ ]:
df.info() # 데이터셋 정보 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   subidr  20 non-null     int64
 1   attnr   20 non-null     object
 2   num1    20 non-null     int64
 3   num2    20 non-null     float64
 4   num3    20 non-null     int64
dtypes: float64(1), int64(3), object(1)
memory usage: 932.0+ bytes

## 2. 핵심 속성 추출

**①-1. 열 단위(1열)로 추출하기**

In [ ]:
# 'attnr'속성 기준으로 열 단위 전체 추출
col=df['attnr']
col

0     divided
1     divided
2     divided
3     divided
4     divided
5     divided
6     divided
7     divided
8     divided
9     divided
10    focused
11    focused
12    focused
13    focused
14    focused
15    focused
16    focused
17    focused
18    focused
19    focused
Name: attnr, dtype: object

In [ ]:
#attnr 속성 기준으로 상위 5개 행 추출
col=df['attnr']
col.head()

0    divided
1    divided
2    divided
3    divided
4    divided
Name: attnr, dtype: object

**①-2. 두 개 이상의 열 추출하기**

In [ ]:
cols=df[['num1','num2']] # 두 개 이상의 열 추출하기
cols.head() # 상위 5개 행 추출

   num1  num2
0     2   4.0
1     3   4.0
2     3   5.0
3     5   7.0
4     4   5.0

**② 행 단위로 추출하기**

In [ ]:
df.loc[2] # 데이터 프레임의 [인덱스 이름]에 해당하는 데이터 추출

subidr          3
attnr     divided
num1            3
num2          5.0
num3            6
Name: 2, dtype: object

In [ ]:
df.loc[2:4]

   subidr    attnr  num1  num2  num3
2       3  divided     3   5.0     6
3       4  divided     5   7.0     5
4       5  divided     4   5.0     8

In [ ]:
df.iloc[2] # 리스트 활용하여 2행 데이터 추출

subidr          3
attnr     divided
num1            3
num2          5.0
num3            6
Name: 2, dtype: object

In [ ]:
df.iloc[2:4] # 슬라이싱 활용하여 데이터 추출

   subidr    attnr  num1  num2  num3
2       3  divided     3   5.0     6
3       4  divided     5   7.0     5

In [ ]:
df.loc()[[1,3,5]]

   subidr    attnr  num1  num2  num3
1       2  divided     3   4.0     5
3       4  divided     5   7.0     5
5       6  divided     5   5.0     6

In [ ]:
df.iloc()[2,[3,4]]

num2    5.0
num3      6
Name: 2, dtype: object

③ 값 대체하기

In [ ]:
df.loc[[0,2],['attnr']] = 'divided*' # 다른 값으로 대체
df['attnr'].head()

0    divided*
1     divided
2    divided*
3     divided
4     divided
Name: attnr, dtype: object

In [ ]:
col_drop = df.drop('subidr',axis=1) # 열 기준으로 삭제
col_drop.head()

      attnr  num1  num2  num3
0  divided*     2   4.0     7
1   divided     3   4.0     5
2  divided*     3   5.0     6
3   divided     5   7.0     5
4   divided     4   5.0     8

### 3. 데이터 전처리

**① 데이터 삭제**

In [ ]:
row_drop = df.drop(3,axis=0) # 행 기준으로 삭제
row_drop.head()

   subidr     attnr  num1  num2  num3
0       1  divided*     2   4.0     7
1       2   divided     3   4.0     5
2       3  divided*     3   5.0     6
4       5   divided     4   5.0     8
5       6   divided     5   5.0     6

**② 결측치 삭제**

In [ ]:
df.loc[[2,3],['num1']] = None # 일부 데이터를 결측치(None)로 제작
df.loc[[1,3],['num2']] = None
df.loc[3,['attnr']] = None
df.head()
print('\n결측치 개수:')
print(df.isnull().sum())

결측치 개수:
subidr    0
attnr     1
num1      2
num2      2
num3      0
dtype: int64

In [ ]:
# 결측치가 있는 행 전체 삭제
row_drop = df.dropna(inplace=False) # inplace 속성 = 원본 데이터 값의 값을 삭제할지 결정(디폴트=false)
row_drop.head()

   subidr     attnr  num1  num2  num3
0       1  divided*   2.0   4.0     7
4       5   divided   4.0   5.0     8
5       6   divided   5.0   5.0     6
6       7   divided   5.0   4.5     6
7       8   divided   5.0   7.0     8

In [ ]:
df.head()

   subidr     attnr  num1  num2  num3
0       1  divided*   2.0   4.0     7
1       2   divided   3.0   NaN     5
2       3  divided*   NaN   5.0     6
3       4      None   NaN   NaN     5
4       5   divided   4.0   5.0     8

In [ ]:
df.dropna(subset=['num1'], inplace=True) # 특정 열(num1)의 결측치가 있는 행만 삭제
df.head()

   subidr     attnr  num1  num2  num3
0       1  divided*   2.0   4.0     7
1       2   divided   3.0   NaN     5
4       5   divided   4.0   5.0     8
5       6   divided   5.0   5.0     6
6       7   divided   5.0   4.5     6

**③ 평균값, 최빈값으로 대체하기**
→ 다시 일부 데이터 값을 none처리 필요

In [ ]:
import seaborn
df = seaborn.load_dataset('anagrams')

df.loc[[2,3],['num1']] = None # 일부 데이터를 결측치(None)로 제작
df.loc[[1,3],['num2']] = None
df.loc[3,['attnr']] = None
df.head()
print('\n결측치 개수:')
print(df.isnull().sum())

결측치 개수:
subidr    0
attnr     1
num1      2
num2      2
num3      0
dtype: int64

In [ ]:
mean_num1=df['num1'].mean() #num1 열의 평균
df['num1']=df['num1'].fillna(mean_num1) # 결측치 채우기
df.head()

   subidr    attnr  num1  num2  num3
0       1  divided   2.0   4.0     7
1       2  divided   3.0   NaN     5
2       3  divided   5.5   5.0     6
3       4     None   5.5   NaN     5
4       5  divided   4.0   5.0     8

In [ ]:
mode_attnr=df['attnr'].mode()[0] #attnr 열의 최빈값
df['attnr']=df['attnr'].fillna(mode_attnr) # 결측치 채우기
df.head()

   subidr    attnr  num1  num2  num3
0       1  divided   2.0   4.0     7
1       2  divided   3.0   NaN     5
2       3  divided   5.5   5.0     6
3       4  focused   5.5   NaN     5
4       5  divided   4.0   5.0     8

In [ ]:
df.loc[[0,2,3],['attnr']] = 'divided*' # 데이터 값 수정
df['attnr'].head()

0    divided*
1     divided
2    divided*
3    divided*
4     divided
Name: attnr, dtype: object

**④ 텍스트값 대체하기**

In [ ]:
df['attnr'] = df['attnr'].str.replace("*", "", regex=False) # * 문자를 공백으로 처리
df['attnr'].head()

0    divided
1    divided
2    divided
3    divided
4    divided
Name: attnr, dtype: object